### ISSUE TITLE
英語を中心に学習されたモデルに日本語で追加学習したもの

### ISSUE THREAD

**Issue by kaisugi** [llm-jp/awesome-japanese-llm#2]
- [NovelAI/genji-jp](https://huggingface.co/NovelAI/genji-jp)
- [izumi-lab/llama-13b-japanese-lora-v0-1ep](https://huggingface.co/izumi-lab/llama-13b-japanese-lora-v0-1ep)
- [izumi-lab/llama-7b-japanese-lora-v0-5ep](https://huggingface.co/izumi-lab/llama-7b-japanese-lora-v0-5ep)
- [lightblue/japanese-mpt-7b](https://huggingface.co/lightblue/japanese-mpt-7b)
- [NTQAI/ChatNTQ-7B-Japanese](https://huggingface.co/NTQAI/ChatNTQ-7B-Japanese)
- [blinkdl/rwkv-4-world-jp55](https://huggingface.co/BlinkDL/rwkv-4-world)
- [llama-2-70b-chat-4bit-japanese-v1](https://huggingface.co/doshisha-mil/llama-2-70b-chat-4bit-japanese-v1)
- [ganchengguang/Yoko-7B-Japanese-v1](https://huggingface.co/ganchengguang/Yoko-7B-Japanese-v1)

参考: https://yuzuai.jp/benchmark

**Comment by ganchengguang** [comment]
こんにちは、横浜国大森研の甘です。最近、LLaMA2を基づいて、日本語のLLMを訓練しました。よろしければ、加えて嬉しいです。また、今後もっと大きいサイズのモデル更新予定です。https://huggingface.co/ganchengguang/Yoko-7B-Japanese-v1

**Comment by kaisugi** [comment]
@ganchengguang ありがとうございます！llama2 を QLoRA チューニングしたものですね 👏 👏

自分の時間の都合上、英語を中心に学習されたモデルに日本語で追加学習したモデルはまだリポジトリに載せられていないのですが、概要だけでも載せられるように検討します！

**Comment by ganchengguang** [comment]
ありがとうございます。
