### ISSUE TITLE
JMMMU

### ISSUE THREAD

**Issue by Silviase** [llm-jp/awesome-japanese-llm#373]
- [Home](https://mmmu-japanese-benchmark.github.io/JMMMU/)
- [Hugging Face](https://huggingface.co/datasets/JMMMU/JMMMU)

**Comment by kaisugi** [comment]
Issue投稿ありがとうございます！！

JMMMUのauthorではないとは思いますが、説明文の欄の紹介文をどうするかについては、ご希望ありますか？
無ければ自分が適当に書いちゃいます。

<img width="800" alt="スクリーンショット 2024-10-09 9 18 05" src="https://github.com/user-attachments/assets/dce85982-74cd-4868-a358-fe2e77a0b35c">

**Comment by Silviase** [comment]
特に希望はありません．

- MMMUの日本語版
- 720のMMMUの翻訳版の問題と600の日本文化特有の新規の問題（Culture-Specific）で，合計1,320の問題から構成される

あたりを含んでいれば良いと思います．
