### ISSUE TITLE
LLM-jp-3 VILA 14B

### ISSUE THREAD

**Issue by kaisugi** [llm-jp/awesome-japanese-llm#397]
https://llm-jp.nii.ac.jp/llm/2024/11/20/llm-jp-3-vila-14b.html

**Comment by ssgw-keito** [comment]
- アーキテクチャ
  - LLaVA-1.5 
- 学習画像/テキスト
  - Japanese image text pairs, LLaVA-Pretrain, Japanese interleaved data, coyo (subset), mmc4-core (subset), llava-instruct-ja, japanese-photos-conv, ja-vg-vqa, synthdog-ja, LLaVA-1.5 instruction data (subset)
- 開発元
  - LLM-jp
- ライセンス
  - [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0) と [the OpenAI terms of use](https://openai.com/policies/terms-of-use) に従う必要がある。
