### ISSUE TITLE
日本語LLMまとめ図にモデル追加のお願い

### ISSUE THREAD

**Issue by ZHAOTING** [llm-jp/awesome-japanese-llm#52]
@kaisugi さん、日本語LLMまとめページの作成ありがとうございます！

パラメタ数・公開時間の図に、rinnaモデルに関する情報の追加をお願いしたいと思いますが。
rinna早期モデルの代表として
* [rinna/japanese-gpt2-small](https://huggingface.co/rinna/japanese-gpt2-small)と[rinna/japanese-gpt2-medium](https://huggingface.co/rinna/japanese-gpt2-medium) は2021年4月に公開されました。
* [rinna/japanese-gpt-1b](https://huggingface.co/rinna/japanese-gpt-1b) は2022年1月に公開されました。

こちらの情報は記事とcommit historyで確認できます。
パラメタ数・公開時間の図に追加してもらえば幸いです！

よろしくお願いします。

**Comment by kaisugi** [comment]
こちらこそいつもありがとうございます！
図を作っているのが実は私ではないので、ちょっと反映までに時間がかかるかもしれませんが、問い合わせておきます！

**Comment by kaisugi** [comment]
遅くなりました。以下でいかがでしょうか？

- https://rinna.co.jp/news/2021/08/20210825.html (0.1B, 0.3Bモデル)
- https://rinna.co.jp/news/2022/01/2022012601.html (1.3Bモデル)

の情報をもとに図をアップデートしました。

![parameter-size-figrue](https://github.com/llm-jp/awesome-japanese-llm/assets/36184621/8ef7d8f1-b081-48df-b30a-a76778f9557f)

**Comment by ZHAOTING** [comment]
@kaisugi さん、ありがとうございます！
こちらは問題ありません。よろしくお願いします。

**Comment by kaisugi** [comment]
画像本体はアップデートしたのですが、GitHub の README に古い画像のキャッシュが残ってしまっているため、しばし反映までお待ちください。
確認次第閉じます。

**Comment by kaisugi** [comment]
READMEの方にも反映されたようですね！
