### ISSUE TITLE
パラメータ数の図の縦軸に単位を追加

### ISSUE THREAD

**Issue by hidetokazawa** [llm-jp/awesome-japanese-llm#67]
パラメータ数の図の縦軸に単位がつけれらていません。おそらく billion だと思いますが、追加した方がよいと思います。

**Comment by kaisugi** [comment]
ご連絡いただきありがとうございます！確かにそうですね...
単位をつけた画像に差し替えます 🙇

**Comment by kaisugi** [comment]
以下の図に差し替えます。

![parameter_size_overview](https://github.com/llm-jp/awesome-japanese-llm/assets/36184621/d9a6b453-b002-48f9-bb62-d3635260806e)

**Comment by kaisugi** [comment]
README、GitHub Pages 双方で単位がつけられた図になったことを確認しましたので、closeさせていただきます。
