### ISSUE TITLE
LLMパラメータサイズの図における NEC の位置

### ISSUE THREAD

**Issue by Negelon** [llm-jp/awesome-japanese-llm#79]
現在の図においては2022/07頃にプロットされていますが、NECのLLMに関するプレスリリースが出たのは2023/07頃なので1年分ずれているように見えます。

https://jpn.nec.com/press/202307/20230706_02.html

**Comment by kaisugi** [comment]
本当ですね... 修正しておきます！ありがとうございます 🙇

**Comment by Negelon** [comment]
ありがとうございます！
よろしくお願いいたします！
